# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-vbguest")
  system('vagrant plugin install vagrant-vbguest')
end

unless Vagrant.has_plugin?("vagrant-reload")
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure("2") do |config|

  config.vm.define "base" do |base|
    base.vm.box = "ubuntu/bionic64"

    base.vm.provider "virtualbox" do |v|
      v.name = "base"
      v.customize ["modifyvm", :id, "--groups", "/vpn"]
    end

    # Full upgrade of the system
    base.vm.provision :shell,
      run: "always",
      inline: "apt-get -y update && apt-get -y dist-upgrade && apt-get update -y --fix-missing",
      privileged: true
    # Install dependencies
    base.vm.provision :shell, path: "base.sh"
    # Reload the VM
    base.vm.provision :reload
  end
end
